# border pixel of windows
borderpx = 2

# snap pixel
snap = 32

# 0 means no bar
showbar = 1

# 0 means bottom bar
topbar = 1

# 0 means no systray
showsystray = 1

# 0 means sloppy systray follows selected monitor. >0 means pin systray to monitor X
systraypinning = 0

# 0 means systray in the right corner. >0 means systray on the left of status text
systrayonleft = 0

# systray spacing
systrayspacing = 2

# 1: if pinning fails, display systray on the first monitor, 0: display systray on the last monitor
systraypinningfailfirst = 1

# font array
fonts = [ "monospace:size=10" ]

# colors
SchemeNorm.ColFg = "#bbbbbb"
SchemeNorm.ColBg = "#222222"
SchemeNorm.Border = "#444444"
SchemeSel.ColFg = "#eeeeee"
SchemeSel.ColBg = "#005577"
SchemeSel.Border = "#005577"

# tagging
tags = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]

# valid properties: class, instance, title, tag, isfloating, monitor
rules = [ { class = "GIMP", isfloating = 1 },
          { class = "Firefox", tag = 8 } ]

# layouts

# factor of master area size [0.05..0.95]
mfact = 0.55

# number of clients in master area
nmaster = 1

# 1 means respect size hints in tiled resizals
resizehints = 1

# 1 will force focus on the fullscreen window
lockfullscreen = 1

layouts = [ { symbol = "[]=",     arrange = "tile" },
            { symbol = "><>",     arrange = "NULL" },
            { symbol = "[M]",     arrange = "monocle" } ]

# see sxhkd / sxhkdrc for keybinds

# button definitions
# click can be ClkTagBar, ClkLtSymbol, ClkStatusText, ClkWinTitle, ClkClientWin, or ClkRootWin
# mask can be super, alt, ctrl, shift
buttons = [ { click = "ClkLtSymbol",    mask = 0,       button = "button1",   function = "setlayout",       argument = { } },
            { click = "ClkLtsymbol",    mask = 0,       button = "button3",   function = "setlayout",       argument = 2 },
            { click = "ClkWinTitle",    mask = 0,       button = "button2",   function = "quit",            argument = { } },
            { click = "ClkStatusText",  mask = 0,       button = "button2",   function = "spawn",           argument = [ "st" ] },
            { click = "ClkClientWin",   mask = "alt",   button = "button1",   function = "movemouse",       argument = { } },
            { click = "ClkClientWin",   mask = "alt",   button = "button2",   function = "togglefloating",  argument = { } },
            { click = "ClkClientWin",   mask = "alt",   button = "button3",   function = "resizemouse",     argument = { } },
            { click = "ClkTagBar",      mask = 0,       button = "button1",   function = "view",            argument = { } },
            { click = "ClkTagBar",      mask = 0,       button = "button3",   function = "toggleview",      argument = { } },
            { click = "ClkTagBar",      mask = "alt",   button = "button1",   function = "tag",             argument = { } },
            { click = "ClkTagBar",      mask = "alt",   button = "button3",   function = "toggletag",       argument = { } } ]
