#!/usr/bin/env sh

signal() {
	xsetroot -name "fsignal:$*"
}

case $# in
1)
	case $1 in
	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit | tagall | togglegaps | defaultgaps | focusstack_inc | focusstack_dec | focusstack_prev | pushstack_inc | pushstack_dec | pushstack_prev)
		signal "$1"
		;;
	*)
		echo "Unknown command or missing one argument."
		exit 1
		;;
	esac
	;;
2)
	case $1 in
	view)
		signal "$1" ui "$2"
		;;
	viewex | toggleviewex | tagex | toggletagex | setlayoutex | focusstack | pushstack | incnmaster | focusmon | tagmon | incrgaps | incrigaps | incrogaps | incrihgaps | incrivgaps | incrohgaps | incrovgaps | shiftview)
		signal "$1" i "$2"
		;;
	setmfact | setcfact)
		signal "$1" f "$2"
		;;
	*)
		echo "Unknown command or one too many arguments."
		exit 1
		;;
	esac
	;;
*)
	echo "Too many arguments."
	exit 1
	;;
esac
